# -*- coding: utf-8 -*-
"""Untitled44.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_nySBj9P8dwBEFMcIbJ9bMFcuZnnwFnK
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import drive
drive.mount('/content/drive/')

df=pd.read_csv("/content/drive/MyDrive/tips.csv")

df.head(10)

"""** Which contain three numeric type column like ‘tips_bill’, ‘tip’ and ‘size’. So, we can plot a histogram for them.**"""

sns.distplot(df["size"])

sns.distplot(df["tip"])

sns.distplot(df["total_bill"])

#Plot Histogram of "total_bill" with kde (kernal density estimator) parameters
sns.distplot(df["total_bill"], kde=False,)

sns.scatterplot(data=df, x="total_bill", y="tip", hue="time", style="time")

sns.pairplot(df, hue ='sex')